language: python
python:
  - "2.7"
install:
  - pip install -r requirements.pip
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput 
script:
  - python manage.py test --noinput
notifications:
  email:
    - didi@rebelproject.org
  flowdock: 232485f7661e644ae5878944c2597042
